apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: env-vars
data:
  github_token: ${GITHUB_TOKEN}
  jcdecaux_api_key: ${JCDECAUX_API_KEY}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: stations
  namespace: openbikes
spec:
  schedule: "*/5 * * * *" # Every 5 minutes
  startingDeadlineSeconds: 300 # 5 minutes
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          restartPolicy: OnFailure
          containers:
            - name: stations
              image: ghcr.io/maxhalford/openbikes:latest
              imagePullPolicy: Always
              command:
                - python
                - /code/fetch_stations.py
                - --commit
                - --push
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: env-vars
                      key: github_token
                - name: JCDECAUX_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: env-vars
                      key: jcdecaux_api_key
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather
  namespace: openbikes
spec:
  schedule: "0 * * * *" # Every 5 minutes
  startingDeadlineSeconds: 1800 # 30 minutes
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          restartPolicy: OnFailure
          containers:
            - name: weather
              image: ghcr.io/maxhalford/openbikes:latest
              imagePullPolicy: Always
              command:
                - python
                - /code/fetch_weather.py
                - --commit
                - --push
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: env-vars
                      key: github_token
