apiVersion: batch/v1
kind: CronJob
metadata:
  name: stations
  namespace: openbikes
spec:
  schedule: "*/5 * * * *" # Every 5 minutes
  startingDeadlineSeconds: 300 # 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          restartPolicy: OnFailure
          containers:
            - name: stations
              image: ghcr.io/MaxHalford/openbikes:latest
              imagePullPolicy: Always
              command:
                - python
                - /bin/fetch_stations.py --commit --push
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather
  namespace: openbikes
spec:
  schedule: "0 * * * *" # Every 5 minutes
  startingDeadlineSeconds: 1800 # 30 minutes
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          restartPolicy: OnFailure
          containers:
            - name: weather
              image: ghcr.io/MaxHalford/openbikes:latest
              imagePullPolicy: Always
              command:
                - python
                - /bin/fetch_weather.py --commit --push
